steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cats-api-graphql", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/cats-api-graphql"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "cats-api-graphql",
        "--image",
        "gcr.io/$PROJECT_ID/cats-api-graphql",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--add-cloudsql-instances",
        "cats-api-257611:europe-west1:catsdb",
        "--update-env-vars",
        "NODE_ENV=production,CLOUD_SQL_CONNECTION_NAME=cats-api-257611:europe-west1:catsdb",
        "--quiet",
      ]
images:
  - gcr.io/$PROJECT_ID/cats-api-graphql
