name: Branch Pipeline

on:
  push:
    branches-ignore: master

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install
  #       run: npm ci
  #     - name: Prettier
  #       run: npm run prettier
  #     - name: Lint
  #       run: npm run lint
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install
  #       run: npm ci
  #     - name: Docker
  #       run: cd ops/docker; ./run-ci.sh
  #     - name: Test
  #       run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud Platform - Deploy
        uses: covertbert/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: beta run deploy cats --quiet --region europe-west1 --image gcr.io/${{secrets.GCLOUD_PROJECT_ID}}/cats --platform managed
