name: Branch Pipeline

on:
  push:
    branches-ignore: master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Prettier
        run: npm run lint
      - name: Lint
        run: npm run prettier
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Docker
        run: cd ops/docker; ./run-ci.sh
      - name: Test
        run: npm run test
