name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Docker
        run: cd docker; ./run-ci.sh
      - name: Test
        run: |
        export DB_HOST=localhost
        echo $DB_HOST
        ./ops/test.sh
